default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: geek_conciergerie_development
  username: soufiane
  password: soufiane
  host: localhost
  port: 5432

test:
  <<: *default
  database: geek_conciergerie_test
  username: soufiane
  password: soufiane
  host: localhost
  port: 5432


production:
  adapter: postgresql
  database: geek_conciergerie_prod
  host:  localhost
  pool: 5
  timeout: 5000
  username: soufiane
  password: soufiane