# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6ca968d5e31bff0efce220ae7d988b444ba1d50b72d70ef968920bc85b73d084e1a3f09a29bd0401290b96bab94843dfe785f4810adc085f15b27c5d9378656

test:
  secret_key_base: d39083d3f9a7691d7617b93af8a65761194751cb35309b13db37fd2a9f30d2654e452982d86bb519665a6036acb9f72e82ff95911ab5e3830588519f55eb932c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
